### ISSUE TITLE
Error with compilation

### ISSUE THREAD

**Issue by ZEREX222** [topaxi/angular-dropdown#17]
Hi, could you fix this problem?

ERROR in src/app/header-filter/header-filter.component.html(103,11): Directive AngularDropdownControlDirective, Property 'isOpen' does not exist on type 'AngularDropdownDirective'. Did you mean '_isOpen$'?
src/app/header-filter/header-filter.component.html(103,11): Directive AngularDropdownControlDirective, Property 'isOpen' does not exist on type 'AngularDropdownDirective'. Did you mean '_isOpen$'?

![image](https://user-images.githubusercontent.com/13930668/70793697-bde2c000-1dbd-11ea-913b-d32d2d1aa828.png)

Thanks a lot!

**Comment by topaxi** [comment]
I'm currently not very active in any angular related projects and therefore won't find any time to work on this issue. I'd be happy to accept a pull request and release a new version though :)

**Comment by topaxi** [comment]
@sokolbird fixed this 👍
