### ISSUE TITLE
Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by codez** [topaxi/angular-dropdown#3]
Occasionally, we receive the following error at `AngularDropdownContentComponent.set [as animationClass]`: "TypeError: Cannot read property 'classList' of null"

It appears that the `dropdownElement` is null sometimes. I guess the method could just early return if this is the case.

**Comment by topaxi** [comment]
Published as `0.5.1`

**Comment by codez** [comment]
Olé, thank you!
