### ISSUE TITLE
Failed run with Angular Universal 

### ISSUE THREAD

**Issue by macwac** [topaxi/angular-dropdown#5]
var closest = ((/** @type {?} */ (window))).Element && Element.prototype.closest
ReferenceError: Element is not defined

Angular CLI: 7.3.8
Node: 11.7.0
OS: linux x64
Angular: 7.2.12
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cli                      7.3.8
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0

**Comment by topaxi** [comment]
Haven't had the time or resources to use this with an Angular Universal project yet, I'd be happy to accept a PR implementing Angular Universal support.

**Comment by macwac** [comment]
@topaxi I open #6, can you check this?

**Comment by topaxi** [comment]
Thanks! Published as 0.5.3.
